on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

run-name: Compile

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v7

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
            version: '6.4.2'
            target: 'desktop'

      - name: Create Project Files
        run: |
          cmake -G "Ninja" -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=staging

      - name: Compile
        run: |
          ninja install -C build
          ls staging
          ls staging/bin
          ls staging/lib

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v7
        with:
          name: q3tod3_map_cli-x86_64-gcc-linux
          path: build/src/cli/q3tod3_map
          retention-days: 1
          if-no-files-found: error

      - name: Upload GUI artifact
        uses: actions/upload-artifact@v7
        with:
          name: q3tod3_map_gui-x86_64-gcc-linux
          path: build/src/gui/q3tod3_map_gui
          retention-days: 1
          if-no-files-found: error
    
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          target: 'desktop'
          arch: 'win64_msvc2022_64'

      - name: Configure Dependencies
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64

      - name: Create Makefiles
        run: |
          cmake -G "Ninja" -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=staging

      - name: Compile
        run: |
          ninja install -C build

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v7
        with:
          name: q3tod3_map_cli-x86_64-msvc-windows
          path: build/Release/q3tod3_map.exe
          retention-days: 1
          if-no-files-found: error

      - name: Upload GUI artifact
        uses: actions/upload-artifact@v7
        with:
          name: q3tod3_map_gui-x86_64-msvc-windows
          path: build/Release/q3tod3_map_gui.exe
          retention-days: 1
          if-no-files-found: error
