on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

run-name: Compile

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v7

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
            version: '6.4.2'
            target: 'desktop'

      - name: Create Project Files
        run: |
          cmake -G "Ninja" -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=staging

      - name: Compile
        run: |
          ninja install -C build

      - name: Upload CLI and GUI artifact
        uses: actions/upload-artifact@v7
        with:
          name: q3tod3_map-binaries-x86_64-gcc-linux
          path: staging/bin
          retention-days: 1
          if-no-files-found: error
    
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.4.2'
          target: 'desktop'
          arch: 'win64_mingw'

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: |
            base-devel
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-toolchain


      - name: Create Makefiles
        run: |
          cmake -G "Ninja" -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=staging

      - name: Compile
        run: |
          ninja install -C build

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v7
        with:
          name: q3tod3_map-binaries-x86_64-mingw-windows
          path: staging
          retention-days: 1
          if-no-files-found: error
