name: Compile

on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v7

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
            version: '6.4.2'
            target: 'desktop'

      # - name: Install Dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y \
      #       g++
      #       make

      - name: Compile
        shell: bash
        run: |
          [ -e build ] || mkdir build
          cd build
          qmake6 ../
          make

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v7
        with:
          name: q3tod3_map_cli-x86_64-gcc-linux
          path: build/src/cli/q3tod3_map
          retention-days: 1
          if-no-files-found: error

      - name: Upload GUI artifact
        uses: actions/upload-artifact@v7
        with:
          name: q3tod3_map_gui-x86_64-gcc-linux
          path: build/src/cli/q3tod3_map
          retention-days: 1
          if-no-files-found: error
    
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.*'
          target: 'desktop'
          arch: 'win64_msvc2022_64'

      # - name: Configure Dependencies
      #   uses: TheMrMilchmann/setup-msvc-dev@v4
      #   with:
      #     arch: x64

      - name: Compile
        shell: bash
        run: |
          [ -e build ] || mkdir build
          cd build
          qmake6 ../
          make

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v7
        with:
          name: q3tod3_map_cli-x86_64-msvc-windows
          path: build/src/cli/q3tod3_map.exe
          retention-days: 1
          if-no-files-found: error

      - name: Upload GUI artifact
        uses: actions/upload-artifact@v7
        with:
          name: q3tod3_map_gui-x86_64-msvc-windows
          path: build/src/gui/q3tod3_map_gui.exe
          retention-days: 1
          if-no-files-found: error
